language: python
sudo: false
python:
  - "2.7"
  - "3.5"
edge: true
notifications:
  slack: metacell:5ALSeoP88DqIhORUJvxE56sq
services:
  - docker
script:
  - docker build -t="neuron-ui" .
  - docker run  -t -dit --name=neuron-ui_container -h localhost -p 8888:8888 neuron_ui
