language: python
sudo: false
python:
  - "2.7"
  - "3.5"
edge: true
notifications:
  slack: metacell:5ALSeoP88DqIhORUJvxE56sq
script:
  - cd utilities
  - python install.py
  - cd ..
  - cd neuron_ui/tests
  - python -m unittest netpyne_model_interpreter_test
